# Generated by Django 4.2.9 on 2024-02-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('uni_id', models.IntegerField()),
                ('group', models.CharField(choices=[('EDU', 'Education'), ('DEV', 'Development'), ('MEDIA', 'Media'), ('OC', 'Operations'), ('ENT', 'Entertainment'), ('HR', 'Human Resources')], max_length=5)),
            ],
        ),
    ]
