# Generated by Django 4.2.9 on 2024-02-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uni_id',
            field=models.IntegerField(max_length=7),
        ),
    ]
