# Generated by Django 4.2.9 on 2024-02-26 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0002_alter_staff_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='uni_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2200000), django.core.validators.MaxValueValidator(2399999)]),
        ),
    ]
