# Generated by Django 4.2.9 on 2024-02-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0003_alter_staff_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='group',
            field=models.CharField(choices=[('EDU', 'Education'), ('DEV', 'Development'), ('MEDIA', 'Media'), ('OC', 'Organization'), ('ENT', 'Entertainment'), ('HR', 'Human Resources')], max_length=5),
        ),
    ]
