# Generated by Django 4.2.9 on 2024-02-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0004_alter_staff_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='group',
        ),
        migrations.AddField(
            model_name='staff',
            name='group',
            field=models.ManyToManyField(to='pivots.group'),
        ),
    ]
